from selenium import webdriver
import time
import random
from selenium.webdriver.common.keys import Keys

print("\33[31m")
print("           ▒█▀▀▀█ █▀▀ █▀▀█ █▀▀█ █▀▀█ █░░█ 　 ▒█▀▀▀█ █▀▀█ █▀▀█ █▀▄▀█ ")
print("           ░▀▀▀▄▄ █░░ █▄▄█ █▄▄▀ █▄▄▀ █▄▄█ 　 ░▀▀▀▄▄ █░░█ █▄▄█ █░▀░█ ")
print("           ▒█▄▄▄█ ▀▀▀ ▀░░▀ ▀░▀▀ ▀░▀▀ ▄▄▄█ 　 ▒█▄▄▄█ █▀▀▀ ▀░░▀ ▀░░░▀ ")
print("\33[34m" + "                                 By Streammet")
print("")
print("\033[0m")

print("\033[33m")

driver = webdriver.Firefox(executable_path="/media/raphael/HDD 1TBx/Nextcloud/Coden/python/scaryspam/geckodriver")
driver.set_window_size(10,740)
driver.set_window_position(2000,2000)
print("1 = Instagram")
print("2 = Facebook (Coming Soon)")
print("3 = Twitter (Coming Soon)")
print("\033[0m")
selection = input("\033[1m" + "\033[42m" + "Choose your Website:" + "\033[0m" + " " + "\33[32m")

if selection == "1":
	driver.get('https://www.instagram.com/accounts/password/reset/')
if selection == "2":
	driver.get('https://www.facebook.com/login/identify')
if selection == "3":
	driver.get('https://twitter.com/account/begin_password_reset')

if selection < "4":
	print()
else:
	print("")
	print("\33[31m" + "Invaild selection")
	print("")
	print("\033[33m")
	print("1 = Instagram")
	print("2 = Facebook (Coming Soon)")
	print("3 = Twitter (Coming Soon)")
	print("\033[0m")
	selection = input("\033[1m" + "\033[42m" + "Choose your Website:" + "\033[0m" + " " + "\33[32m")

	if selection == "1":
		driver.get('https://www.instagram.com/accounts/password/reset/')
	if selection == "2":
		driver.get('https://www.facebook.com/login/identify')
	if selection == "3":
		driver.get('https://twitter.com/account/begin_password_reset')

vname = input("\033[0m" + "\033[1m" + "\033[42m" + "Type the Victoms Emal,Username or Phone number:" + "\033[0m" + " " + "\033[0m" + "\33[32m")

driver.find_element_by_xpath('//*[@name="cppEmailOrUsername"]').send_keys(vname)

print("\033[0m")
snum = input("\033[1m" + "\033[42m" + "How often(Choose from 1-10):" + "\033[0m" + " " + "\33[32m")

if snum == "1":
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "1 Send")
if snum == "2":
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "1 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "2 Send")
if snum == "3":
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "1 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "2 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "3 Send")
if snum == "4":
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "1 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "2 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "3 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "4 Send")
	time.sleep(1)
if snum == "5":
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "1 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "2 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "3 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "4 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "5 Send")
	time.sleep(1)
if snum == "6":
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "1 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "2 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "3 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "4 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "5 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "6 Send")
	time.sleep(1)
if snum == "7":
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "1 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "2 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "3 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "4 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "5 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "6 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "7 Send")
	time.sleep(1)
if snum == "8":
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "1 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "2 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "3 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "4 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "5 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "6 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "7 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "8 Send")
	time.sleep(1)
if snum == "9":
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "1 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "2 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "3 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "4 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "5 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "6 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "7 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "8 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "9 Send")
	time.sleep(1)
if snum == "10":
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "1 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "2 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "3 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "4 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "5 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "6 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "7 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "8 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "9 Send")
	time.sleep(1)
	driver.find_element_by_xpath('//*[@type="button"]').click()
	print("\33[92m" + "10 Send")
	time.sleep(1)


driver.quit()

